import React from 'react';

const CVFooter: React.FC = () => {
  return (
    <div className="bg-gray-100 px-6 py-3 border-t">
      <div className="flex items-center justify-between">
        <div className="flex flex-col gap-1">
          <p className="text-xs text-gray-600 font-medium">Generated by ExcellyGen LMS</p>
          <p className="text-xs text-gray-500">Generated on: {new Date().toLocaleDateString('en-US', { 
            year: 'numeric', 
            month: 'long', 
            day: 'numeric' 
          })}</p>
        </div>
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 bg-blue-900 rounded flex items-center justify-center">
            <span className="text-white text-xs font-bold">EG</span>
          </div>
          <span className="text-xs font-bold text-gray-700">ExcellyGen</span>
        </div>
      </div>
    </div>
  );
};

export default CVFooter;