import React from 'react';

const CVFooter: React.FC = () => {
  return (
    <div className="bg-gray-50 px-8 py-4 border-t">
      <div className="flex items-center justify-between">
        <div className="flex flex-col gap-1">
          <p className="text-sm text-gray-500">Generated by Excelly Gen LMS</p>
          <p className="text-xs text-gray-400">Generated on: {new Date().toLocaleDateString('en-US', { 
            year: 'numeric', 
            month: 'long', 
            day: 'numeric' 
          })}</p>
        </div>
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 bg-gradient-to-r from-purple-600 to-pink-500 rounded flex items-center justify-center">
            <span className="text-white text-xs font-bold">[G]</span>
          </div>
          <span className="text-sm font-medium text-gray-700">Excelly Gen</span>
        </div>
      </div>
    </div>
  );
};

export default CVFooter;